### ISSUE TITLE
Unable to retrieve metadata for some DOIs

### ISSUE THREAD

**Issue by sfisher** [datacite/spinone#42] opened 2018-06-08 22:20 UTC
I read over the documentation at https://support.datacite.org/docs/api which gives examples for retrieving metadata for a specific identifier like this:

```
curl https://api.datacite.org/works/10.5438/0012
```

That particular example works great, but if I try identifiers such as I find on PubMed or other public sources it seems like I can't get metadata for them, though the DOIs resolve.

For example, these first 20 random DOIs I found on the internet give 404s and don't return any metadata:

```
curl https://api.datacite.org/works/10.1093/jme/tjy088
curl https://api.datacite.org/works/10.1093/ee/nvy084
curl https://api.datacite.org/works/10.1111/tbed.12916
curl https://api.datacite.org/works/10.1038/d41586-018-04938-z
curl https://api.datacite.org/works/10.1207/s15328023top1703_12
curl https://api.datacite.org/works/10.1016/j.cedpsych.2008.04.002
curl https://api.datacite.org/works/10.1119/1.4935763
curl https://api.datacite.org/works/10.1071/Zo08044
curl https://api.datacite.org/works/10.1371/journal.pone.0057745
curl https://api.datacite.org/works/10.2305/IUCN.UK.2008.RLTS.T40540A10331066.en
curl https://api.datacite.org/works/10.1126/science.1200674
curl https://api.datacite.org/works/10.1111/j.1365-294X.2007.03399.x
curl https://api.datacite.org/works/10.1016/j.biocon.2007.11.007
curl https://api.datacite.org/works/10.1038/s41586-018-0036-z
curl https://api.datacite.org/works/10.1103/PhysRevLett.119.080503
curl https://api.datacite.org/works/10.1632/pmla.2016.131.2.430
curl https://api.datacite.org/works/10.1108/eb014124
curl https://api.datacite.org/works/10.1119/1.1848514
curl https://api.datacite.org/works/10.1137/1.9781611971132
curl https://api.datacite.org/works/10.1038/nphys4343
```

Thanks.

**Comment by daslerr** [comment] 2018-06-11 15:20
I'm going to close this issue, because this is expected behavior. 

Our API retrieves information about DOIs for which DataCite is the registration agency. It does not retrieve information about all DOIs that exist. The DOIs in your list are not DataCite DOIs. They all seem to be journals, so my guess is that they're most likely Crossref DOIs, since Crossref largely covers the publishing domain. You could use the Crossref API (https://api.crossref.org/) to search for them instead.

**Closed as completed by daslerr** 2018-06-11 15:20 UTC

**Comment by sfisher** [comment] 2018-06-11 18:47
Thank you!  It seems as though using a different API such as

```curl -v -LH "Accept: application/citeproc+json" http://doi.org/10.15146/R38302```

Is more appropriate for obtaining citation metadata and returns citation metadata reliably for all the DOIs I've tried and I got directed to the wrong API to use.
