### ISSUE TITLE
NULL values in author (creators) fields

### ISSUE THREAD

**Issue by bozyurt** [datacite/spinone#17] opened 2017-04-26 21:12 UTC
While using the DATS API https://api.datacite.org/dats?publisher-id=BL.BGI
The authors have sometimes null values e.g.
 "creators": [
      {
        "first-name": null,
        "last-name": null
      },
      {
        "first-name": null,
        "last-name": null
      },
      {
        "first-name": "Ning",
        "last-name": "Huang"
      },
      {
        "first-name": "Feng",
        "last-name": "Liu"
      },
      {
        "first-name": null,
        "last-name": null
      },
      {
        "first-name": null,
        "last-name": null
      },
      {
        "first-name": "Waqar",
        "last-name": "Ahmad"
      },
      {
        "first-name": null,
        "last-name": null
      },

while In datacite (https://data.datacite.org/10.5524/100223 ) 
The XML for creators in datacite looks like this:
<creators>
-<creator>
<creatorName>Eric Earl</creatorName>
</creator>
-<creator>
<creatorName>Damion V Demeter</creatorName>
<nameIdentifier nameIdentifierScheme="ORCID" schemeURI="http://orcid.org/">0000-0003-1931-3587</nameIdentifier>
</creator>
-<creator>
<creatorName>Kate Mills</creatorName>
<nameIdentifier nameIdentifierScheme="ORCID" schemeURI="http://orcid.org/">0000-0002-6463-186X</nameIdentifier>
</creator>
-<creator>
<creatorName>Glad Mihai</creatorName>
</creator>
-<creator>
<creatorName>Luka Ruzic</creatorName>
</creator>
-<creator>
<creatorName>Nick Ketz</creatorName>
</creator>
-<creator>
<creatorName>Andrew Reineberg</creatorName>
</creator>
-<creator>
<creatorName>Marianne C Reddan</creatorName>
</creator>
-<creator>
<creatorName>Anne-Lise Goddings</creatorName>
<nameIdentifier nameIdentifierScheme="ORCID" schemeURI="http://orcid.org/">0000-0003-4779-8956</nameIdentifier>
</creator>
-<creator>
<creatorName>Javier Gonzalez-Castillo</creatorName>
<nameIdentifier nameIdentifierScheme="ORCID" schemeURI="http://orcid.org/">0000-0002-6520-5125</nameIdentifier>
</creator>
-<creator>
<creatorName>Krzysztof J Gorgolewski</creatorName>
<nameIdentifier nameIdentifierScheme="ORCID" schemeURI="http://orcid.org/">0000-0003-3321-7583</nameIdentifier>
</creator>
</creators>

**Comment by kjgarza** [comment] 2018-04-20 11:13
this is actually a small nice bug. I'm wondering would it be worth to include Bolognese here? I guess the validations are better.

**Comment by kjgarza** [comment] 2018-04-20 12:59
Ok, we really need to do something about how we storing the metadata. For example, this DOI 10.5524/100223 has different `looking` metadata in the MDS, in Contentet-Negotiatio / Fabrica, and in the REST API. Four different looking versions. they look different. Very much related to https://github.com/datacite/datacite/issues/350

I think there is not a bug in this one it's just that the orignal author was confused by all the differences and metadata and so did I when checking them. 

@mfenner I think I will close it.

**Comment by mfenner** [comment] 2018-04-20 14:08
Please close this issue. https://github.com/datacite/datacite/issues/350 only fixes metadata storing going forward. The small amount of metadata in the production system registered via EZ API or Fabrica before this bug was fixed is still affected. The fix is not a code change, but updating the metadata so that it is stored correctly in the MDS. Maybe best done with a separate issue.

**Closed as completed** 2018-04-20 14:24 UTC
